import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/dashboard');
  await page.getByRole('button', { name: 'Employees' }).click();
  await page.getByRole('link', { name: 'L List' }).click();
  await page.getByRole('button', { name: 'Departments' }).click();
  await page.getByRole('link', { name: 'L List' }).click();
  await page.getByRole('button', { name: 'Positions' }).click();
  await page.getByRole('link', { name: 'L List' }).click();
  await page.getByRole('button', { name: 'Salary Ranges' }).click();
  await page.getByRole('link', { name: 'L List' }).click();
  await page.getByRole('button').filter({ hasText: 'account_circle' }).click();
  await page.getByRole('menuitem', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('ashtyn1');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Pa$$word123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Employees' }).click();
  await page.getByRole('link', { name: 'C Create' }).click();
  await page.getByRole('button', { name: 'Departments' }).click();
  await page.getByRole('link', { name: 'C Create' }).click();
  await page.getByRole('button', { name: 'Positions' }).click();
  await page.getByRole('link', { name: 'C Create' }).click();
  await page.getByRole('button', { name: 'Salary Ranges' }).click();
  await page.getByRole('link', { name: 'C Create' }).click();
  await page.getByRole('button').filter({ hasText: 'account_circle' }).click();
  await page.getByRole('menuitem', { name: 'logout' }).click();
  await page.getByRole('link', { name: 'here' }).click();
});